- name: Delete openshift cluster on Classic infra.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml
    
    - name: Check is cluster Exists
      ibm_container_cluster_info:
        cluster_name_id: "{{ cluster_name }}"
      failed_when:
        - cluster_output.rc != 0
        - '"cluster could not be found" not in cluster_output.stderr'
      register: cluster_output

    - name: Save Cluster info as fact
      set_fact:
        cacheable: True
        cluster_info: "{{ cluster_output.resource }}"
      when: cluster_output.rc==0
    
    - name: Destroy Openshift Cluster
      ibm_container_cluster:
        name: "{{ cluster_name }}"
        id: "{{ cluster_info.id }}"
        state: absent
      register: cluster_destroy_output
      when: cluster_info.id is defined 