namespace: "ibmcloud"
name: "ansible_collection"
version: "1.2.2"
dependencies:
readme: "README.md"
authors:
    - "Jay W Carman"
    - "Anilkumar C M"
license:
    - "MPL-2.0"
tags:
    - ibmcloud
    - terraform
repository: "https://github.com/IBM-Cloud/ansible-collection-ibm"
